---
title: "AppDevelopment"
author: "Madhi Saranadasa"
date: '2022-06-14'
output: html_document
---

```{r}

library(tidyverse)
library(ggmap)
library(leaflet)
library(lubridate)
library(htmltools)
library(RColorBrewer)

register_google(key = 'AIzaSyCBWs3C3m6xv36WH3ZLYyMigr7jecT5p00')

projectfolder <- dirname(getwd())
datafolder <- file.path(projectfolder, "Data")

```

# Load data

```{r}

filenames <- list.files(datafolder)
filenames <- filenames[str_detect(filenames, "CTD")]
filenames <- str_remove(filenames, ".csv")

filepaths <- list.files(datafolder, full.names = TRUE)
filepaths <- filepaths[str_detect(filepaths, "CTD")]

for (i in 1:length(filepaths)) {
  temp <- read_csv(filepaths[i])
  assign(filenames[i], temp)
}

```

```{r}



study_list <- CTD_DetailsClean %>%
      filter(year(start_date == input$YearSlider)) %>% 
      distinct(id) %>%
      pull(id)



testlist <- CTD_Details %>% 
  filter(agency == "Madghi") %>%
  pull(id)

test <- CTD_Details %>% 
  filter(id %in% testlist)


markercolors <- c('red', 'darkred', 'orange', 'green', 'darkgreen', 'blue', 'purple', 'darkpurple', 'cadetblue')
idmapping <- tibble(id = testlist,
                    color = rep_len(markercolors, length(testlist)))


length(testlist)


test1 <- c(1, 2, 3, 4)
test2 <- c(3,4)

intersect(test1, test2)
```


# CTD_LocationAdded: Geocode cities (if needed)

```{r}

location_info <- CTD_Location %>%
  mutate(locstring = paste(city, state, country)) %>%
  mutate(combined = str_remove(locstring, "NA")) 

#CTD_LocationAdded <- mutate_geocode(location_info, locstring)

CTD_LocationAdded <- CTD_LocationAdded %>%
  mutate(markerID = row_number()) %>%
  select(markerID, id, city, state, country, lon, lat)

datafolder <- file.path(projectfolder, "Data", "CTD_LocationAdded.csv")
write_csv(CTD_LocationAdded, datafolder)

```

# CTD_DetailsClaim: Clean up CTD_Details 

```{r}

date_vars <- c("start_date",
               "completion_date",
               "primary_completion_date")

convertDate <- function(x) {
  temp = case_when(str_detect(x, ",") ~ x,
                   !is.na(x) ~ paste0(word(x, 1), " 1, ", word(x, 2)))
  
  temp = mdy(temp)
}

CTD_Details[date_vars] <- lapply(CTD_Details[date_vars], convertDate)

CTD_DetailsClean <- CTD_Details

datapath <- file.path(projectfolder, "Data", "CTD_DetailsClean.csv")
write_csv(CTD_DetailsClean, datapath)

```

# Add more context to locations

```{r}

markercolors <- c('red', 'darkred', 'orange', 'green', 'darkgreen', 'blue', 'purple', 'darkpurple', 'cadetblue')

study_list <- CTD_DetailsClean %>%
      filter(year(start_date) == 2014) %>%
      distinct(id)
    
if(nrow(study_list) == 0) {
  
  locations <- CTD_LocationAdded %>%
    inner_join(study_list, by = "id") %>%
    mutate(label = paste0(id))
} else {
  
  idmapping <- tibble(id = study_list$id,
                      color = brewer.pal(length(study_list$id), "Paired"))
  
  locations <- CTD_LocationAdded %>%
    inner_join(study_list, by = "id") %>%
    inner_join(idmapping, by = "id") %>%
    mutate(label = paste0(id))
  
}

locations

test <- CTD_DetailsClean %>%
  mutate(year = year(start_date)) %>%
  group_by(year) %>%
  summarise(n = n()) %>%
  filter(!is.na(year))
```

```{r}

ggplot() +
  geom_bar(data = test,
            aes(x = year,
                y = n),
           stat = "identity") 
  scale_y_continuous(limits = c(0, NA))

```

```{r}

us_flag <- CTD_LocationAdded %>% 
  filter(country == "United States") %>%
  distinct(id) %>%
  mutate(has_us_facility = TRUE) 

parser <- CTD_DetailsClean %>%
  select(id, title, ie) %>%
  left_join(us_flag, by = "id") %>%
  mutate(has_us_facility = ifelse(is.na(has_us_facility), FALSE, has_us_facility)) %>%
  mutate(conditions = "Non-cystic Fibrosis Bronchiectasis") %>%
  rename(nct_id = id,
         eligibility_criteria = ie) %>%
  select(nct_id, title, has_us_facility, conditions, eligibility_criteria) 



datapath <- file.path(projectfolder, "Data", "CTD_Eligibility_criteria.csv")
write_csv(parser, datapath)

```



