---
title: "AppDevelopment"
author: "Madhi Saranadasa"
date: '2022-06-14'
output: html_document
---

```{r}

library(tidyverse)
library(ggmap)
library(leaflet)
library(lubridate)
library(htmltools)
library(RColorBrewer)

```

# Load data

```{r}

projectfolder <- dirname(getwd())
datafolder <- file.path(projectfolder, "Data")

filenames <- list.files(datafolder)
filenames <- filenames[str_detect(filenames, "CTD")]
filenames <- str_remove(filenames, ".csv")

filepaths <- list.files(datafolder, full.names = TRUE)
filepaths <- filepaths[str_detect(filepaths, "CTD")]

for (i in 1:length(filepaths)) {
  temp <- read_csv(filepaths[i])
  assign(filenames[i], temp)
}

rm(temp)

```

# CTD_LocationAdded: Geocode cities (if needed)

```{r}

location_info <- CTD_Location %>%
  mutate(locstring = paste(city, state, country)) %>%
  mutate(combined = str_remove(locstring, "NA")) 

#CTD_LocationAdded <- mutate_geocode(location_info, locstring)

CTD_LocationAdded <- CTD_LocationAdded %>%
  mutate(markerID = row_number()) %>%
  select(markerID, id, city, state, country, lon, lat)

datafolder <- file.path(projectfolder, "Data", "CTD_LocationAdded.csv")
write_csv(CTD_LocationAdded, datafolder)

```

# CTD_DetailsClaim: Clean up CTD_Details

```{r}

date_vars <- c("start_date",
               "completion_date",
               "primary_completion_date")

convertDate <- function(x) {
  temp = case_when(str_detect(x, ",") ~ x,
                   !is.na(x) ~ paste0(word(x, 1), " 1, ", word(x, 2)))
  
  temp = mdy(temp)
}

CTD_Details[date_vars] <- lapply(CTD_Details[date_vars], convertDate)

CTD_DetailsClean <- CTD_Details

datapath <- file.path(projectfolder, "Data", "CTD_DetailsClean.csv")
write_csv(CTD_DetailsClean, datapath)

```

# CTD_FlagInclusion

```{r}

keywords <- tribble(~newvar, ~pattern,
                    "Exacerbation", "exacerbation",
                    "PA", "pseudo|aeruginosa",
                    "Sputum", "sputum|mucous",
                    "CT", "tomography|imaging",
                    "Antibiotics", "antibiotic|treatment|regimen",
                    "Spirometry", "fev1|spirometry")

frame <- CTD_DetailsClean %>%
  distinct(id)

for(i in 1:nrow(keywords)){
  
  matches <- CTD_Eligibility_criteria %>%
    filter(str_detect(str_to_lower(eligibility_criteria), keywords$pattern[i])) %>%
    distinct(nct_id) %>%
    pull(nct_id)
  
  frame[[keywords$newvar[i]]] = ifelse(frame$id %in% matches, TRUE, FALSE)

}

frame <- frame %>% 
  pivot_longer(-id, names_to = "keyword", values_to = "value") %>%
  filter(value)

datapath <- file.path(projectfolder, "Data", "CTD_FlagInclusion.csv")
datapath
write_csv(frame, datapath)

```

# CTD_FlagEndpoints

```{r}

keywords <- tribble(~newvar, ~pattern,
                    "Exacerbation", "exacerbation",
                    "QOL", "quality|qol",
                    "Spirometry", "fev|pulmonary function|spirometry")

frame <- CTD_DetailsClean %>%
  distinct(id)

alloutcomes <- bind_rows(CTD_Outcome1, CTD_Outcome2)

for(i in 1:nrow(keywords)){
  
  matches <- alloutcomes %>%
    filter(str_detect(str_to_lower(measure), keywords$pattern[i])) %>%
    distinct(id) %>%
    pull(id)
  
  frame[[keywords$newvar[i]]] = ifelse(frame$id %in% matches, TRUE, FALSE)

}

frame <- frame %>% 
  pivot_longer(-id, names_to = "keyword", values_to = "value") %>%
  filter(value)

datapath <- file.path(projectfolder, "Data", "CTD_FlagOutcome.csv")
write_csv(frame, datapath)

```

# CTD_FlagSponser

```{r}

keywords <- tribble(~newvar, ~pattern,
                    "Bayer", "bayer",
                    "Gilead", "gilead",
                    "Novartis", "novartis",
                    "Insmed", "insmed",
                    "Aradigm", "aradigm",
                    "AstraZeneca", "zeneca")

frame <- CTD_DetailsClean %>%
  distinct(id)

for(i in 1:nrow(keywords)){
  
  matches <- CTD_DetailsClean %>%
    filter(str_detect(str_to_lower(agency), keywords$pattern[i])) %>%
    distinct(id) %>%
    pull(id)
  
  frame[[keywords$newvar[i]]] = ifelse(frame$id %in% matches, TRUE, FALSE)

}

frame <- frame %>% 
  pivot_longer(-id, names_to = "keyword", values_to = "value") %>%
  filter(value)

datapath <- file.path(projectfolder, "Data", "CTD_FlagSponser")
write_csv(frame, datapath)

```

# CTD_FlagMed

```{r}

keywords <- tribble(~newvar, ~pattern,
                    "Azithromycin", "azithromycin",
                    "Ciprofloxacin ", "cipro")

frame <- CTD_DetailsClean %>%
  distinct(id)

for(i in 1:nrow(keywords)){
  
  matches <- CTD_Intervention %>%
    filter(str_detect(str_to_lower(intervention_name), keywords$pattern[i])) %>%
    distinct(id) %>%
    pull(id)
  
  frame[[keywords$newvar[i]]] = ifelse(frame$id %in% matches, TRUE, FALSE)

}

frame <- frame %>% 
  pivot_longer(-id, names_to = "keyword", values_to = "value") %>%
  filter(value)

datapath <- file.path(projectfolder, "Data", "CTD_FlagMed")
write_csv(frame, datapath)

```
